//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;

namespace Thomsen.NumberWizard
{
	public class Guesser
	{
		public double currentMax;
		public double guess;
		public object Guess (double min, double max, KeyCode code)
		{

			if (code == KeyCode.UpArrow) {
				guess = System.Math.Round ((max - guess )/ 2);
				return guess;
			} else
			if (code == KeyCode.DownArrow) {
				guess = System.Math.Round ((guess - (double)min) / 2);
				currentMax = guess;
				return guess;
			}
				return null;
		}

	}

}
