//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace NumberWizardWithTests
{
	[TestFixture()]
	public class Test
	{
		[Test()]
		public void TestCase ()
		{
		}
	}
}

